// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9DEwKgtw1pXSMfsrtihqxseuZdsQt7Ds',
    appId: '1:216835986009:web:b480186cf51ee758c0d748',
    messagingSenderId: '216835986009',
    projectId: 'aetherium-salon',
    authDomain: 'aetherium-salon.firebaseapp.com',
    storageBucket: 'aetherium-salon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pnUJIv1pA2yYyWnhYYvshLMk6xTwrBc',
    appId: '1:216835986009:android:158b1171922672c0c0d748',
    messagingSenderId: '216835986009',
    projectId: 'aetherium-salon',
    storageBucket: 'aetherium-salon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj8Ffh2QZbEnHwBy3K_vqTKjguK5zcTGQ',
    appId: '1:216835986009:ios:c82027a1bfaeb673c0d748',
    messagingSenderId: '216835986009',
    projectId: 'aetherium-salon',
    storageBucket: 'aetherium-salon.appspot.com',
    iosClientId: '216835986009-c1ika74p5pk0svc9aob3rfbrs71akl2a.apps.googleusercontent.com',
    iosBundleId: 'it.esteticaaurea.aetheriumSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj8Ffh2QZbEnHwBy3K_vqTKjguK5zcTGQ',
    appId: '1:216835986009:ios:c82027a1bfaeb673c0d748',
    messagingSenderId: '216835986009',
    projectId: 'aetherium-salon',
    storageBucket: 'aetherium-salon.appspot.com',
    iosClientId: '216835986009-c1ika74p5pk0svc9aob3rfbrs71akl2a.apps.googleusercontent.com',
    iosBundleId: 'it.esteticaaurea.aetheriumSalon',
  );
}
